# Generated by Django 4.2 on 2023-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_category', models.CharField(choices=[('TP', 'Terrestrial Planet'), ('GGP', 'Gas Giant')], max_length=3)),
            ],
        ),
    ]
