# Generated by Django 4.2 on 2023-05-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets_app', '0002_planettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planets_app.planettype'),
        ),
    ]
