# Generated by Django 4.2 on 2023-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets_app', '0004_planet_day_length_planet_distance_sun_planet_gravity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosphericComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(choices=[('H', 'Hydrogen'), ('HE', 'Helium'), ('CH4', 'Methane'), ('CO2', 'Carbon Dioxide'), ('N', 'Nitrogen'), ('AR', 'Argon'), ('O', 'Oxygen'), ('SO2', 'Sulfur Dioxide'), ('NA', 'Sodium'), ('K', 'Potassium')], default='H', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='planet',
            name='year_length',
        ),
    ]
