# Generated by Django 4.2 on 2023-05-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets_app', '0005_atmosphericcomposition_remove_planet_year_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(choices=[('H', 'Hydrogen'), ('HE', 'Helium'), ('CH4', 'Methane'), ('CO2', 'Carbon Dioxide'), ('N', 'Nitrogen'), ('AR', 'Argon'), ('O', 'Oxygen'), ('SO2', 'Sulfur Dioxide'), ('NA', 'Sodium'), ('K', 'Potassium')], default='H', max_length=3, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AtmosphericComposition',
        ),
    ]
