# Generated by Django 4.2 on 2023-05-06 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets_app', '0006_substance_delete_atmosphericcomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosphericComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('planet', models.ManyToManyField(to='planets_app.planet')),
                ('substance', models.ManyToManyField(to='planets_app.substance')),
            ],
        ),
    ]
