# Generated by Django 4.2 on 2023-05-07 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets_app', '0008_remove_atmosphericcomposition_planet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='day_length',
        ),
        migrations.AlterField(
            model_name='planet',
            name='radius',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='revolution',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='rotation',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
